---
title: "mlm_gcm_fpca"
author: "Suryadyuti Baral"
date: "`r Sys.Date()`"
output: html_document
---

# Dependencies
```{r}
library(fda)
library(fdapace)
library(ggplot2)
library(lavaan)
library(tidyr)
library(dplyr)
library(lme4)
library(MASS)
library(purrr)
source("Rfunctions_gcm_fpca.R")
```

```{r eval=FALSE, include=FALSE}
Ly_ht <- lapply(seq_len(ncol(fda::growth$hgtf)), function(i) fda::growth$hgtf[,i])
Lt_ht <- lapply(seq_len(ncol(fda::growth$hgtf)), function(i) (fda::growth$age - min(fda::growth$age))/(max(fda::growth$age - min(fda::growth$age))))
fpca_ht <- FPCA(Ly_ht, Lt_ht)
plot(fpca_ht)

fit_ng_ht <- ConvertSupport(fromGrid = fpca_ht$workGrid,
                                      toGrid = time,
                                      phi = fpca_ht$phi)
matplot(fit_ng_ht[,1:2], type = "l")
```

# Parameters

```{r}
set.seed(12)

# Relevant parameters to be modified
n_subj <- 500
time <- seq(0, 1, length.out = 12)
rho_ss2 <- 0     # correlation between slope and slope 2

# ----- Functions -------
#f1_t <- sqrt(48/7) * time - (3/4) * (sqrt(48/7))
#f2_t <- sqrt(5) * time^2

f1_t <- fit_ng_ht[,1]
f2_t <- fit_ng_ht[,2]

#f1_t <- sqrt(12) * time - sqrt(12)/2
#f2_t <- rep(1, n_time)
```


# The Rest
```{r}
n_time <- length(time)
missingness = .3

# ----- fixed effects -----
beta_s <- 1
beta_s2 <- 1

# ----- Random effects -----
sigma_s <- 1   # SD of random slope
sigma_s2 <- sqrt(2)  # SD of random slope for quadratic slope

Sigma <- matrix(c(sigma_s^2, rho_ss2 * sigma_s * sigma_s2,
                  rho_ss2 * sigma_s * sigma_s2, sigma_s2^2), 2, 2)

# Draw random effects (b_i = intercept deviation, s_i = slope deviation)
b_s <- MASS::mvrnorm(n_subj, mu = c(0, 0), Sigma = Sigma)
s_i <- b_s[, 1]
s2_i <- b_s[, 2]

# Within-curve noise
sigma_eps <- 0.5
```


```{r}
# ----- Generate data -----
Y <- matrix(NA, nrow = n_subj, ncol = n_time)
for (i in 1:n_subj) {
  Y[i, ] <- (beta_s + s_i[i]) * f1_t  + (beta_s2 + s2_i[i]) * f2_t + rnorm(n_time, 0, sigma_eps)
}

#x = Sparsify(Y, pts = time, 6, fragment = TRUE)
#Y_miss = LyLt_to_Y(x$Ly, x$Lt, time)
Y_miss <- introduce_missingness(Y, missingness)
Y_quad_split <- train_test_split(Y_miss) 
Y_quad <- Y_quad_split$train


```

```{r}
set.seed(123)
n_sample <- 10
sample_ids <- sample(1:nrow(Y_quad), n_sample)

# Convert to data frame for ggplot
df_plot <- data.frame(
  id = rep(sample_ids, each = length(time)),
  time = rep(time, times = n_sample),
  y = as.vector(t(Y_quad[sample_ids, ]))
)

df_plot_clean <- df_plot |>
  dplyr::filter(
    !is.na(time),
    !is.na(y)
  )

# Plot
ggplot(
  df_plot_clean,
  aes(x = time, y = y, color = factor(id), group = id)
) +
  geom_line(alpha = 0.6, linewidth = 0.6) +
  geom_point(size = 2) +
  theme_minimal(base_size = 14) +
  labs(
    title = paste("Random Sample of", n_sample, "Subjects with Quadratic Functions"),
    x = "Time",
    y = "Y(t)",
    color = "Subject ID"
  ) +
  theme(legend.position = "none")

```

```{r}
# ----- Apply FPCA -----
Ly_quad <- lapply(seq_len(nrow(Y_quad)), function(i) Y_quad[i,])
Lt_quad <- lapply(seq_len(nrow(Y_quad)), function(i) time)

fpca_quad <- FPCA(Ly_quad, Lt_quad)
fit_ng <- ConvertSupport(fromGrid = fpca_quad$workGrid,
                                      toGrid = time,
                                      phi = fpca_quad$phi)
plot(fpca_quad)
```
```{r eval=FALSE, include=FALSE}
# ----- Apply FPCA -----
Ly_quad_c <- lapply(seq_len(nrow(Y_quad)), function(i) Y_quad[i,] - mean(Y_quad[i,], na.rm = TRUE))
Lt_quad <- lapply(seq_len(nrow(Y_quad)), function(i) time)

fpca_quad_c <- FPCA(Ly_quad_c, Lt_quad)
fit_ng_c <- ConvertSupport(fromGrid = fpca_quad_c$workGrid,
                                      toGrid = time,
                                      phi = fpca_quad_c$phi)
plot(fpca_quad_c)
```

```{r}
Y_test <- Y_quad_split$test
loading1 <- fit_ng[,1]
loading2 <- fit_ng[,2]

dat_lav <- as.data.frame(Y_test)
colnames(dat_lav) <- paste0("y", 1:n_time)
l1 <- paste0(loading1, "*y", 1:n_time, collapse = " + ")
l2 <- paste0(loading2, "*y", 1:n_time, collapse = " + ")

growth_mod <- paste0("
  eta1 =~ ", l1, "
  eta2 =~ ", l2, "

  # latent variances & covariance
  eta1 ~~ eta1
  eta2 ~~ eta2
  eta1 ~~ eta2

  # constant residual variance across time
  ", paste0(colnames(dat_lav), " ~~ vare*", colnames(dat_lav), collapse = "\n"), "
")

fit <- growth(
  model = growth_mod,
  data  = dat_lav,
  missing = "fiml", 
  em.h1.iter.max = 10000 
)

summary(fit, standardized = TRUE, fit.measures = TRUE)
```

```{r}
dat_long <- as.data.frame(Y_test) |>
  mutate(id = seq_len(nrow(Y_test))) |>
  pivot_longer(
    cols = -id,
    names_to = "time",
    values_to = "y"
  )

dat_long$f1 <- rep(fit_ng[,1], nrow(Y_test))
dat_long$f2 <- rep(fit_ng[,2], nrow(Y_test))

fit_lmer <- lmer(
  y ~ 0 + f1 + f2 + (0 + f1 + f2 | id),
  data = dat_long,
  REML = TRUE
)

fit_null <- lmer(
  y ~ 1 + (1 | id),
  data = dat_long,
  REML = TRUE
)

#McFadden's pseudo r^2
1 - (logLik(fit_lmer)/logLik(fit_null))
```
```{r}
Y_train <- Y_quad_split$train
betas = paste0("beta", 2:(n_time - 1))
loading1 <- rep(1, n_time)
loading2 <- c(0, betas, 1)

dat_lav <- as.data.frame(Y_train)
colnames(dat_lav) <- paste0("y", 1:n_time)
l1 <- paste0(loading1, "*y", 1:n_time, collapse = " + ")
l2 <- paste0(loading2, "*y", 1:n_time, collapse = " + ")

growth_mod <- paste0("
  eta1 =~ ", l1, "
  eta2 =~ ", l2, "

  # latent variances & covariance
  eta1 ~~ eta1
  eta2 ~~ eta2
  eta1 ~~ eta2

  # constant residual variance across time
  ", paste0(colnames(dat_lav), " ~~ vare*", colnames(dat_lav), collapse = "\n"), "
")

fit <- growth(
  model = growth_mod,
  data  = dat_lav,
  missing = "fiml", 
  em.h1.iter.max = 10000 
)

fit_est = summary(fit, standardized = TRUE, fit.measures = TRUE)
loading2_est <- c(0, fit_est$pe[fit_est$pe$label %in% betas,"est"], 1)

Y_test <- Y_quad_split$test
dat_lav <- as.data.frame(Y_test)
colnames(dat_lav) <- paste0("y", 1:n_time)
l1 <- paste0(loading1, "*y", 1:n_time, collapse = " + ")
l2 <- paste0(loading2_est, "*y", 1:n_time, collapse = " + ")

growth_mod <- paste0("
  eta1 =~ ", l1, "
  eta2 =~ ", l2, "

  # latent variances & covariance
  eta1 ~~ eta1
  eta2 ~~ eta2
  eta1 ~~ eta2

  # constant residual variance across time
  ", paste0(colnames(dat_lav), " ~~ vare*", colnames(dat_lav), collapse = "\n"), "
")

fit <- growth(
  model = growth_mod,
  data  = dat_lav,
  missing = "fiml", 
  em.h1.iter.max = 10000 
)

summary(fit, standardized = TRUE, fit.measures = TRUE)
```



```{r eval=FALSE, include=FALSE}
Y_test <- Y_quad_split$test
loading1 <- rep(1, n_time)
loading2 <- fit_ng_c[,1]

dat_lav <- as.data.frame(Y_test)
colnames(dat_lav) <- paste0("y", 1:n_time)
l1 <- paste0(loading1, "*y", 1:n_time, collapse = " + ")
l2 <- paste0(loading2, "*y", 1:n_time, collapse = " + ")

growth_mod_c <- paste0("
  eta1 =~ ", l1, "
  eta2 =~ ", l2, "

  # latent variances & covariance
  eta1 ~~ eta1
  eta2 ~~ eta2
  eta1 ~~ eta2

  # constant residual variance across time
  ", paste0(colnames(dat_lav), " ~~ vare*", colnames(dat_lav), collapse = "\n"), "
")

fit_c <- growth(
  model = growth_mod_c,
  data  = dat_lav,
  missing = "fiml", 
  em.h1.iter.max = 10000 
)

summary(fit_c, standardized = TRUE, fit.measures = TRUE)
```

```{r eval=FALSE, include=FALSE}
loading1 <- rep(1, n_time)
loading2 <- seq(0, 1, length.out = n_time)
l1 <- paste0(loading1, "*y", 1:n_time, collapse = " + ")
l2 <- paste0(loading2, "*y", 1:n_time, collapse = " + ")

growth_mod_param <- paste0("
  eta1 =~ ", l1, "
  eta2 =~ ", l2, "

  # latent variances & covariance
  eta1 ~~ eta1
  eta2 ~~ eta2
  eta1 ~~ eta2

  # constant residual variance across time
  ", paste0(colnames(dat_lav), " ~~ vare*", colnames(dat_lav), collapse = "\n"), "
")

fit_param <- growth(
  model = growth_mod_param,
  data  = dat_lav,
  missing = "fiml", 
  em.h1.iter.max = 10000 
)

summary(fit_param, standardized = TRUE, fit.measures = TRUE)
```

```{r eval=FALSE, include=FALSE}
dat_long <- as.data.frame(Y_test) |>
  mutate(id = seq_len(nrow(Y_test))) |>
  pivot_longer(
    cols = -id,
    names_to = "time",
    values_to = "y"
  )

dat_long$f1 <- rep(fit_ng_c[,1], nrow(Y_test))

fit_lmer_c <- lmer(
  y ~ 1 + f1 + (1 + f1 | id),
  data = dat_long,
  REML = TRUE
)

fit_null <- lmer(
  y ~ 1 + (1 | id),
  data = dat_long,
  REML = TRUE
)

#McFadden's pseudo r^2
1 - (logLik(fit_lmer_c)/logLik(fit_null))
anova(fit_null,fit_lmer_c)
```


