---
title: "nlys analysis"
author: "Suryadyuti Baral"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
library(fdapace)
nlsy <- read.csv("nlsy.csv", na.strings = ".")
age_grid <- seq(6, 14, by = 1)
df_read <- nlsy[!is.na(nlsy$read),]
split_df <- split(df_read, df_read$id)
Ly <- lapply(split_df, function(d) d$read)
Lt <- lapply(split_df, function(d) d$age)
fpca_read <- FPCA(Ly, Lt)
plot(fpca_read)

fit_ng_read <- ConvertSupport(fromGrid = fpca_read$workGrid,
                                      toGrid = age_grid,
                                      phi = fpca_read$phi)

time <- fpca_read$obsGrid

matplot(fit_ng_read[,1:2], type = "l")
```

```{r}
Y <- LyLt_to_Y(Ly, Lt, time)

set.seed(1)
Y_split <- train_test_split(Y) 
Y_tr <- Y_split$train

set.seed(123)
n_sample <- 50
sample_ids <- sample(1:nrow(Y_tr), n_sample)

# Convert to data frame for ggplot
df_plot <- data.frame(
  id = rep(sample_ids, each = length(time)),
  time = rep(time, times = n_sample),
  y = as.vector(t(Y_tr[sample_ids, ]))
)

df_plot_clean <- df_plot |>
  dplyr::filter(
    !is.na(time),
    !is.na(y)
  )

# Plot
ggplot(
  df_plot_clean,
  aes(x = time, y = y, color = factor(id), group = id)
) +
  geom_line(alpha = 0.6, linewidth = 0.6) +
  geom_point(size = 2) +
  theme_minimal(base_size = 14) +
  labs(
    title = paste("Random Sample of", n_sample, "Subjects and Reading Data"),
    x = "Time",
    y = "Y(t)",
    color = "Subject ID"
  ) +
  theme(legend.position = "none")

```
```{r}
# ----- Apply FPCA -----
Ly_tr <- lapply(seq_len(nrow(Y_tr)), function(i) Y_tr[i,] - mean(Y_tr[i,], na.rm = TRUE))
Lt_tr <- lapply(seq_len(nrow(Y_tr)), function(i) time)

fpca_tr <- FPCA(Ly_tr, Lt_tr)
fit_ng_tr <- ConvertSupport(fromGrid = fpca_tr$workGrid,
                                      toGrid = age_grid,
                                      phi = fpca_tr$phi)
plot(fpca_tr)
matplot(fit_ng_tr[,1:2], type = "l")
```
```{r}
Y_test <- Y_split$test
Y_bin <- bin_time_matrix(Y_test, fpca_tr$obsGrid, age_grid, check = TRUE)

loading0 <- rep(1,length(age_grid))
loading1 <- fit_ng_tr[,1]
loading2 <- fit_ng_tr[,2]

dat_lav <- as.data.frame(Y_bin)
colnames(dat_lav) <- paste0("y", 1:length(age_grid))
l0 <- paste0(loading0, "*y", 1:length(age_grid), collapse = " + ")
l1 <- paste0(loading1, "*y", 1:length(age_grid), collapse = " + ")
l2 <- paste0(loading2, "*y", 1:length(age_grid), collapse = " + ")

growth_mod <- paste0("
  eta0 =~ ", l0, "
  eta1 =~ ", l1, "
  eta2 =~ ", l2, "

  # latent variances & covariance
  eta0 ~~ eta0
  eta1 ~~ eta1
  eta2 ~~ eta2
  eta0 ~~ eta1
  eta0 ~~ eta2
  eta1 ~~ eta2

  # constant residual variance across time
  ", paste0(colnames(dat_lav), " ~~ vare*", colnames(dat_lav), collapse = "\n"), "
")

fit <- growth(
  model = growth_mod,
  data  = dat_lav,
  missing = "fiml", 
  em.h1.iter.max = 10000 
)

summary(fit, standardized = TRUE, fit.measures = TRUE)
```

```{r}
loading0 <- rep(1,length(age_grid))
loading1 <- seq(0,1, length.out = length(age_grid))
loading2 <- seq(0,1, length.out = length(age_grid))^2

dat_lav <- as.data.frame(Y_bin)
colnames(dat_lav) <- paste0("y", 1:length(age_grid))
l0 <- paste0(loading0, "*y", 1:length(age_grid), collapse = " + ")
l1 <- paste0(loading1, "*y", 1:length(age_grid), collapse = " + ")
l2 <- paste0(loading2, "*y", 1:length(age_grid), collapse = " + ")

growth_mod_param <- paste0("
  eta0 =~ ", l0, "
  eta1 =~ ", l1, "
  eta2 =~ ", l2, "

  # latent variances & covariance
  eta0 ~~ eta0
  eta1 ~~ eta1
  eta2 ~~ eta2
  eta0 ~~ eta1
  eta0 ~~ eta2
  eta1 ~~ eta2

  # constant residual variance across time
  ", paste0(colnames(dat_lav), " ~~ vare*", colnames(dat_lav), collapse = "\n"), "
")

fit <- growth(
  model = growth_mod_param,
  data  = dat_lav,
  missing = "fiml", 
  em.h1.iter.max = 10000 
)

summary(fit, standardized = TRUE, fit.measures = TRUE)
```

